const GET_CART = "GET_CART";
const ADD_CART = "ADD_CART";
const REMOVE_CART = "REMOVE_CART";
const UPDATE_CART = "UPDATE_CART";
const EMPTY_CART = "EMPTY_CART";
const CHANGE_STATUS = "CHANGE_STATUS";

export default {
  GET_CART,
  ADD_CART,
  REMOVE_CART,
  UPDATE_CART,
  EMPTY_CART,
  CHANGE_STATUS,
};
